title: "Greg Curl"
description: "Data Engineering, Analytics, and Writing"
url: "https://gregcurl.dev"

remote_theme: "nmistakes/minimal-mistakes"

markdown: kramdown
permalink: /:categories/:title
paginate: 6
paginate_path: /blog/page:num

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: single, author_profile: true, read_time: true, share: true }
  - scope: { path: "", type: "projects" }
    values: { layout: single, author_profile: true }

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme
